import { PortfolioActionItem } from './portfolio-manager-actions.data';

export const portfolioManagerActionItems: PortfolioActionItem[] = [
  // ==================== OVERDUE (4 items) ====================
  {
    id: 'PM-ACT-OD-01',
    date: '2026-05-12',
    label: 'UAE Research map',
    project: 'Project Status Report',
    targetType: 'project',
    type: 'Status reports',
    kind: 'report',
    tone: 'blue',
    owner: 'MH',
    ownerName: 'Muna Hasan',
    meta: 'May 12 (Overdue by 5 days)',
    cta: 'Open',
    column: 'Overdue'
  },
  {
    id: 'PM-ACT-OD-02',
    date: '2026-05-10',
    label: 'NEOM Integration readiness',
    project: 'NEOM Integration',
    targetType: 'project',
    type: 'Risk',
    kind: 'risk',
    tone: 'red',
    owner: 'AH',
    ownerName: 'Ahmed Hassan',
    meta: 'May 10 (Overdue by 2 days)',
    cta: 'Open',
    column: 'Overdue'
  },
  {
    id: 'PM-ACT-OD-03',
    date: '2026-05-09',
    label: 'Smart service adoption uplift',
    project: 'Smart City Alpha',
    targetType: 'project',
    type: 'Benefits',
    kind: 'benefit',
    tone: 'green',
    owner: 'FA',
    ownerName: 'Fatima Qahtani',
    meta: 'May 9 (Overdue by 3 days)',
    cta: 'Open',
    column: 'Overdue'
  },
  {
    id: 'PM-ACT-OD-04',
    date: '2026-05-11',
    label: 'Review Project Plans',
    project: 'Vision 2030',
    targetType: 'project',
    type: 'Plans',
    kind: 'plan',
    tone: 'blue',
    owner: 'SA',
    ownerName: 'Sarah Al Saud',
    meta: 'May 11 (Overdue by 1 day)',
    cta: 'Open',
    column: 'Overdue'
  },

  // ==================== THIS WEEK (6 items) ====================
  {
    id: 'PM-ACT-TW-01',
    date: '2026-05-14',
    label: 'Annual Performance Review',
    project: 'Forum Name',
    targetType: 'project',
    type: 'Governance committee',
    kind: 'governance',
    tone: 'blue',
    owner: 'FA',
    ownerName: 'Fatima Qahtani',
    meta: 'May 14 (Due in 2 days)',
    cta: 'Open',
    column: 'This week'
  },
  {
    id: 'PM-ACT-TW-02',
    date: '2026-05-15',
    label: 'Assess Change Request',
    project: 'UAE Research Map',
    targetType: 'project',
    type: 'Change requests',
    kind: 'change',
    tone: 'blue',
    owner: 'MH',
    ownerName: 'Muna Hasan',
    meta: 'May 15 (Due in 3 days)',
    cta: 'Open',
    column: 'This week'
  },
  {
    id: 'PM-ACT-TW-03',
    date: '2026-05-16',
    label: 'Review Dependency',
    project: 'Vision 2030',
    targetType: 'project',
    type: 'Plans',
    kind: 'plan',
    tone: 'blue',
    owner: 'SA',
    ownerName: 'Sarah Al Saud',
    meta: 'May 16 (Due in 4 days)',
    cta: 'Open',
    column: 'This week'
  },
  {
    id: 'PM-ACT-TW-04',
    date: '2026-05-13',
    label: 'Review Report',
    project: 'Smart City Alpha',
    targetType: 'project',
    type: 'Status reports',
    kind: 'report',
    tone: 'blue',
    owner: 'SA',
    ownerName: 'Sarah Al Saud',
    meta: 'May 13 (Due in 1 day)',
    cta: 'Open',
    column: 'This week'
  },
  {
    id: 'PM-ACT-TW-05',
    date: '2026-05-15',
    label: 'Assess Integration exposure',
    project: 'NEOM Integration',
    targetType: 'project',
    type: 'Risk',
    kind: 'risk',
    tone: 'red',
    owner: 'AH',
    ownerName: 'Ahmed Hassan',
    meta: 'May 15 (Due in 3 days)',
    cta: 'Open',
    column: 'This week'
  },
  {
    id: 'PM-ACT-TW-06',
    date: '2026-05-16',
    label: 'Review Benefit',
    project: 'Vision 2030',
    targetType: 'project',
    type: 'Benefits',
    kind: 'benefit',
    tone: 'green',
    owner: 'MH',
    ownerName: 'Muna Hasan',
    meta: 'May 16 (Due in 4 days)',
    cta: 'Open',
    column: 'This week'
  },

  // ==================== UPCOMING (12 items) ====================
  {
    id: 'PM-ACT-UC-01',
    date: '2026-05-20',
    label: 'Benefit Realization',
    project: 'Vision 2030',
    targetType: 'project',
    type: 'Benefits',
    kind: 'benefit',
    tone: 'green',
    owner: 'MH',
    ownerName: 'Muna Hasan',
    meta: 'May 20 (Due in 8 days)',
    cta: 'Open',
    column: 'Upcoming'
  },
  {
    id: 'PM-ACT-UC-02',
    date: '2026-05-22',
    label: 'Review Change requests',
    project: 'NEOM Integration',
    targetType: 'project',
    type: 'Change requests',
    kind: 'change',
    tone: 'blue',
    owner: 'AH',
    ownerName: 'Ahmed Hassan',
    meta: 'May 22 (Due in 10 days)',
    cta: 'Open',
    column: 'Upcoming'
  },
  {
    id: 'PM-ACT-UC-03',
    date: '2026-05-26',
    label: 'Smart service adoption risk',
    project: 'Smart City Alpha',
    targetType: 'project',
    type: 'Risk',
    kind: 'risk',
    tone: 'red',
    owner: 'FA',
    ownerName: 'Fatima Qahtani',
    meta: 'May 26 (Due in 14 days)',
    cta: 'Open',
    column: 'Upcoming'
  },
  {
    id: 'PM-ACT-UC-04',
    date: '2026-05-28',
    label: 'Governance Committee Review',
    project: 'NEOM Integration',
    targetType: 'project',
    type: 'Governance committee',
    kind: 'governance',
    tone: 'blue',
    owner: 'AH',
    ownerName: 'Ahmed Hassan',
    meta: 'May 28 (Due in 16 days)',
    cta: 'Open',
    column: 'Upcoming'
  },
  {
    id: 'PM-ACT-UC-05',
    date: '2026-05-25',
    label: 'UAE Research map (Project name)',
    project: 'UAE Research Map',
    targetType: 'project',
    type: 'Plans',
    kind: 'plan',
    tone: 'blue',
    owner: 'MH',
    ownerName: 'Muna Hasan',
    meta: 'May 25 (Due in 13 days)',
    cta: 'Open',
    column: 'Upcoming'
  },
  {
    id: 'PM-ACT-UC-06',
    date: '2026-05-27',
    label: 'UAE Research map (Project / Program / Portfolio name)',
    project: 'UAE Research Map',
    targetType: 'project',
    type: 'Status reports',
    kind: 'report',
    tone: 'blue',
    owner: 'SA',
    ownerName: 'Sarah Al Saud',
    meta: 'May 27 (Due in 15 days)',
    cta: 'Open',
    column: 'Upcoming'
  },
  {
    id: 'PM-ACT-UC-07',
    date: '2026-05-29',
    label: 'Benefit Name',
    project: 'Vision 2030',
    targetType: 'project',
    type: 'Benefits',
    kind: 'benefit',
    tone: 'green',
    owner: 'MH',
    ownerName: 'Muna Hasan',
    meta: 'May 29 (Due in 17 days)',
    cta: 'Open',
    column: 'Upcoming'
  },
  {
    id: 'PM-ACT-UC-08',
    date: '2026-05-26',
    label: 'Change Request Title',
    project: 'UAE Research Map',
    targetType: 'project',
    type: 'Change requests',
    kind: 'change',
    tone: 'blue',
    owner: 'FA',
    ownerName: 'Fatima Qahtani',
    meta: 'May 26 (Due in 14 days)',
    cta: 'Open',
    column: 'Upcoming'
  },
  {
    id: 'PM-ACT-UC-09',
    date: '2026-05-26',
    label: 'Benefit Name',
    project: 'Vision 2030',
    targetType: 'project',
    type: 'Risk',
    kind: 'risk',
    tone: 'red',
    owner: 'AH',
    ownerName: 'Ahmed Hassan',
    meta: 'May 26 (Due in 14 days)',
    cta: 'Open',
    column: 'Upcoming'
  },
  {
    id: 'PM-ACT-UC-10',
    date: '2026-05-26',
    label: 'Annual Performance Review (Meeting name)',
    project: 'Forum Name',
    targetType: 'project',
    type: 'Governance committee',
    kind: 'governance',
    tone: 'blue',
    owner: 'FA',
    ownerName: 'Fatima Qahtani',
    meta: 'May 26 (Due in 14 days)',
    cta: 'Open',
    column: 'Upcoming'
  },
  {
    id: 'PM-ACT-UC-11',
    date: '2026-05-26',
    label: 'UAE Research map (Project name)',
    project: 'UAE Research Map',
    targetType: 'project',
    type: 'Plans',
    kind: 'plan',
    tone: 'blue',
    owner: 'MH',
    ownerName: 'Muna Hasan',
    meta: 'May 26 (Due in 14 days)',
    cta: 'Open',
    column: 'Upcoming'
  },
  {
    id: 'PM-ACT-UC-12',
    date: '2026-05-26',
    label: 'UAE Research map (Project / Program / Portfolio name)',
    project: 'UAE Research Map',
    targetType: 'project',
    type: 'Status reports',
    kind: 'report',
    tone: 'blue',
    owner: 'SA',
    ownerName: 'Sarah Al Saud',
    meta: 'May 26 (Due in 14 days)',
    cta: 'Open',
    column: 'Upcoming'
  }
];
